In [32]:
import math
import numpy as np
import pandas as pd

import bokeh
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
output_notebook()

Loading BokehJS ...

In [2]:
n = 100
xi = np.array([i/n for i in range(1,n+1)]).reshape(n,-1)
xi.shape

(100, 1)

In [3]:
yi = np.sin(2 * math.pi * xi) + 0.1 * np.random.normal(size = (n,1))
yi.shape

(100, 1)

Create  $\phi_j (x) = x^j$ for $ K = 1,2,3$

In [4]:
X = np.concatenate((np.ones(shape=(n,1)), xi, xi**2, xi**3), axis =1)
B_hat = np.linalg.inv(X.T @ X) @ X.T @ yi
print(B_hat)
y_predicted = X @ B_hat

p = figure(width = 500, height = 300)
p.scatter(x= xi.flatten(), y= yi.flatten(), color = 'black', size = 6)

p.line(x= xi.flatten(), y = y_predicted.flatten(),  line_color = 'red', 
      legend_label = 'y_hat', line_width = 1.5 )

show(p)

[[ -0.23244367]
 [ 12.07017765]
 [-34.72286931]
 [ 23.11438581]]


### Polynomials are not the fastest shifting objects

#### Case 1

In [33]:
n = 100
xi = np.array([i/n for i in range(1,n+1)]).reshape(n,-1)
yi = np.exp(-1000*(xi-0.5)**2) + 0.1 * np.random.normal(size=(n,1))

# K = 10 
X = np.concatenate((np.ones(shape=(n,1)), xi, xi**2, xi**3, xi**4,xi**5,xi**6,xi**7,xi**8,xi**9,xi**10), axis =1)
B_hat = np.linalg.inv(X.T @ X) @ X.T @ yi
y_predicted = X @ B_hat

# Plotting
p = figure(width = 500, height = 300)
p.line(x= xi.flatten(), y= yi.flatten(), color = 'black') # Raw Data
p.line(x= xi.flatten(), y = y_predicted.flatten(),  line_color = 'red', 
      legend_label = 'y_hat', line_width = 1.5 ) # Predicted
show(p)

#### Case 2

In [38]:
n = 100
xi = np.array([i/n for i in range(1,n+1)]).reshape(n,-1)
yi = np.exp(-100*(xi-0.5)**2) + 0.1 * np.random.normal(size=(n,1))

# K = 10 
X = np.concatenate((np.ones(shape=(n,1)), xi, xi**2, xi**3, xi**4, xi**5,xi**6,xi**7,xi**8,xi**9,xi**10), axis =1)
B_hat = np.linalg.inv(X.T @ X) @ X.T @ yi
y_predicted = X @ B_hat

# Plotting
p = figure(width = 500, height = 300, title = 'Polynomial K = 10')
p.scatter(x= xi.flatten(), y= yi.flatten(), color = 'black') # Raw Data
p.line(x= xi.flatten(), y = y_predicted.flatten(),  line_color = 'red', 
      legend_label = 'y_hat', line_width = 1.5 ) # Predicted
show(p)

### Polynomials Spline

In [61]:
n = 100
xi = np.array([i/n for i in range(1,n+1)]).reshape(n,-1)
yi = np.exp(-100*(xi-0.5)**2) + 0.1 * np.random.normal(size=(n,1))


K = 5
poly_splines = np.concatenate(
                (np.where(xi - 0.2 > 0, (xi-0.2)**K, 0),
                np.where(xi - 0.4 > 0, (xi-0.4)**K, 0),
                np.where(xi - 0.6 > 0, (xi-0.6)**K, 0), 
                np.where(xi - 0.8 > 0, (xi-0.8)**K, 0)), axis = 1)

X = np.concatenate((np.ones(shape=(n,1)), xi, xi**2, xi**3, xi**4, poly_splines), axis =1)
B_hat = np.linalg.inv(X.T @ X) @ X.T @ yi
y_predicted = X @ B_hat


In [64]:
df.head(10)

1   x^1     x^2       x^3           x^4  (x-0.2)^K  (x-0.4)^K  (x-0.6)^K  \
0  1.0  0.01  0.0001  0.000001  1.000000e-08        0.0        0.0        0.0   
1  1.0  0.02  0.0004  0.000008  1.600000e-07        0.0        0.0        0.0   
2  1.0  0.03  0.0009  0.000027  8.100000e-07        0.0        0.0        0.0   
3  1.0  0.04  0.0016  0.000064  2.560000e-06        0.0        0.0        0.0   
4  1.0  0.05  0.0025  0.000125  6.250000e-06        0.0        0.0        0.0   
5  1.0  0.06  0.0036  0.000216  1.296000e-05        0.0        0.0        0.0   
6  1.0  0.07  0.0049  0.000343  2.401000e-05        0.0        0.0        0.0   
7  1.0  0.08  0.0064  0.000512  4.096000e-05        0.0        0.0        0.0   
8  1.0  0.09  0.0081  0.000729  6.561000e-05        0.0        0.0        0.0   
9  1.0  0.10  0.0100  0.001000  1.000000e-04        0.0        0.0        0.0   

   (x-0.8)^K  
0        0.0  
1        0.0  
2        0.0  
3        0.0  
4        0.0  
5        0.0  
6        0.0  
7        0.0  
8        0.0  
9        0.0

In [58]:
df = pd.DataFrame(X)
df.columns = [1, 'x^1', 'x^2', 'x^3', 'x^4', '(x-0.2)^K','(x-0.4)^K','(x-0.6)^K', '(x-0.8)^K' ]
df.head(10)

1   x^1     x^2       x^3           x^4  (x-0.2)^K  (x-0.4)^K  (x-0.6)^K  \
0  1.0  0.01  0.0001  0.000001  1.000000e-08        0.0        0.0        0.0   
1  1.0  0.02  0.0004  0.000008  1.600000e-07        0.0        0.0        0.0   
2  1.0  0.03  0.0009  0.000027  8.100000e-07        0.0        0.0        0.0   
3  1.0  0.04  0.0016  0.000064  2.560000e-06        0.0        0.0        0.0   
4  1.0  0.05  0.0025  0.000125  6.250000e-06        0.0        0.0        0.0   
5  1.0  0.06  0.0036  0.000216  1.296000e-05        0.0        0.0        0.0   
6  1.0  0.07  0.0049  0.000343  2.401000e-05        0.0        0.0        0.0   
7  1.0  0.08  0.0064  0.000512  4.096000e-05        0.0        0.0        0.0   
8  1.0  0.09  0.0081  0.000729  6.561000e-05        0.0        0.0        0.0   
9  1.0  0.10  0.0100  0.001000  1.000000e-04        0.0        0.0        0.0   

   (x-0.8)^K  
0        0.0  
1        0.0  
2        0.0  
3        0.0  
4        0.0  
5        0.0  
6        0.0  
7        0.0  
8        0.0  
9        0.0

In [ ]:
# Plotting
p = figure(width = 500, height = 300, title = 'Polynomial Splines K = 5 L = 4')
p.scatter(x= xi.flatten(), y= yi.flatten(), color = 'black') # Raw Data
p.line(x= xi.flatten(), y = y_predicted.flatten(),  line_color = 'red', 
      legend_label = 'y_hat', line_width = 1.5 ) # Predicted
show(p)

In [62]:
df.shape

(100, 9)

In [63]:
X[:,8]

array([0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.0000

In [54]:
np.where(xi - 0.2 > 0, (xi-0.2)**K, 0)

array([[0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.00000000e-10],
       [3.20000000e-09],
       [2.43000000e-08],
       [1.02400000e-07],
       [3.12500000e-07],
       [7.77600000e-07],
       [1.68070000e-06],
       [3.27680000e-06],
       [5.90490000e-06],
       [1.00000000e-05],
       [1.61051000e-05],
       [2.48832000e-05],
       [3.71293000e-05],
       [5.37824000e-05],
       [7.59375000e-05],
       [1.04857600e-04],
       [1.41985700e-04],
       [1.88956800e-04],
       [2.47609900e-04],
       [3.20000000e-04],


In [50]:
X = np.arange(6).reshape(6, 1)

In [51]:
X

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])