In [2]:
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
from scipy.stats import f

x = np.random.standard_normal(size = (100,))


In [5]:
n = 100

In [28]:
x1 = np.random.standard_normal(size = (n,))
x2 = 0.9*x1 + 0.01*np.random.standard_normal(size = (n))
# Create observation by adding error term
y = x1 + 2 * x2 + np.random.standard_normal(size = (n))
X = np.stack((x1,x2), axis=1)
beta_hat = np.linalg.inv(X.T @ X) @ X.T @ y
beta_hat

array([ 20.82054137, -20.14432124])

In [16]:
array([10.82490066, -9.00699383])
array([-3.45470684,  6.82319185])
array([ 3.11369316, -0.28808413])

NameError: name 'array' is not defined

In [29]:
W = np.sum(x1**2) * np.sum(x2**2) - (np.sum(x1*x2))**2

In [30]:
W

1.0173207641109911